server:
    port: 8020 

# Discovery Server Access
eureka:
  client: 
    serviceUrl:
      registerWithEureka: false
      fetchRegistry: false

      defaultZone: http://localhost:8090/eureka/
      