server:
    port: 8030 

# Discovery Server Access
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
      
spring:
    datasource:
        url: jdbc:mysql://localhost/lindpro
        username: root
        password: 1234
      
      
