server:
    port: 8040 

# Discovery Server Access
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

spring:
    datasource:
        url: jdbc:mysql://xxxxxx:3306/Lindpro?useSSL=false
        username: xxxxx
        password: xxxxx
      
     
